os: osx
language: objective-c
matrix:
  include:
    - osx_image: xcode8.2
      env: PLAT=iOS SWFT=3.0
    - osx_image: xcode8.3
      env: PLAT=iOS SWFT=3.1
    - osx_image: xcode9
      env: PLAT=iOS SWFT=3.2
    - osx_image: xcode9
      env: PLAT=iOS SWFT=4.0

before_install:
  - export UUID=$(instruments -s | ruby -e "ARGF.each_line{ |ln| ln =~ /iPhone SE .* \[(.*)\]/; if \$1; puts(\$1); exit; end }")

install:
  - carthage bootstrap --platform iOS

script:
  - set -o pipefail
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID "$UUID"
  - xcodebuild -scheme PMKAddressBook -destination "id=$UUID" clean build SWIFT_VERSION=$SWFT
  - xcodebuild -scheme PMKAddressBook -destination "id=$UUID" test
